# Generated by Django 6.0 on 2026-05-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('trainee_barista', 'Стажёр-бариста'), ('barista', 'Бариста'), ('senior_barista', 'Старший бариста'), ('cook', 'Повар'), ('manager', 'Менеджер'), ('admin', 'Администратор')], default='trainee_barista', max_length=20, verbose_name='Роль'),
        ),
    ]
