# Generated by Django 6.0 on 2026-05-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='goal',
            field=models.TextField(blank=True, verbose_name='Цель модуля'),
        ),
    ]
