# Generated by Django 6.0 on 2026-05-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_add_module_goal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Программа обучения', 'verbose_name_plural': 'Программы обучения'},
        ),
        migrations.AddField(
            model_name='program',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер программы'),
        ),
    ]
